kind: Service
apiVersion: v1
metadata:
  name: postgresql-service
  namespace: default
  labels:
    app: postgresql
spec:
  ports:
    - name: http
      protocol: TCP
      #      port = port connected to ingress
      port: 5432
      # targetPort = port on container
      targetPort: 5432
  selector:
    app: postgresql
  type: NodePort
  sessionAffinity: None
  externalTrafficPolicy: Cluster
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: postgresql
spec:
  selector:
    matchLabels:
      app: postgresql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: postgresql
    spec:
      containers:
        - image: saul/postgresql:latest
          imagePullPolicy: Never
          name: postgresql-container
#          command: ["/bin/sh"]
#          args: ["-c","postgres && sleep 30s && psql -d test_db --user=test_user -a -f restore.sql"]
          env:
            # Use secret in real usage
            - name: POSTGRES_USER
              value: test_user
            - name: POSTGRES_DB
              value: test_db
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysecrets
                  key: POSTGRES_PASSWORD
          ports:
            - containerPort: 5432
              name: postgresql
          volumeMounts:
            - name: postgresql-persistent-storage
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgresql-persistent-storage
          persistentVolumeClaim:
            claimName: postgresql-pv-claim