apiVersion: apps/v1
kind: Deployment
metadata:
  name: graphql-deployment
  labels:
    app: graphql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: graphql
  template:
    metadata:
      labels:
        app: graphql
    spec:
      containers:
        - name: graphql-container
          image: saul/graphql:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 3000
          envFrom:
            - configMapRef:
                name: global-config
          resources:
            limits:
              memory: "200Mi"
              cpu: "100m"
            requests:
              memory: "50Mi"
              cpu: "50m"