apiVersion: v1
kind: Pod
metadata:
  name: redis
  namespace: default
  labels:
    app: redis
spec:
  containers:
    - name: redis-container
      image: saul/redis:latest
      imagePullPolicy: Never
      ports:
        - containerPort: 6379
#      envFrom:
#        - configMapRef:
#            name: global-config
      resources:
        limits:
          cpu: "0.1"
          memory: "400Mi"
      volumeMounts:
        - mountPath: /redis-master-data
          name: data
  volumes:
    - name: data
      emptyDir: {}
---
kind: Service
apiVersion: v1
metadata:
  name: redis-service
  namespace: default
spec:
  ports:
    - port: 6379
      # targetPort = port on container
      targetPort: 6379
  selector:
    app: redis