apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: es-data
  namespace: default
  labels:
    app: es-data
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: {}
