apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fa-config
  namespace: default
  labels:
    app: fa-config
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: {}
