apiVersion: v1
kind: Service
metadata:
  name: fusionauth
  namespace: default
  labels:
    app: fusionauth
spec:
  ports:
  - name: "9011"
    port: 9011
    targetPort: 9011
  selector:
    app: fusionauth
  type: NodePort
  sessionAffinity: None
  externalTrafficPolicy: Cluster
status:
  loadBalancer: {}
