apiVersion: v1
kind: Service
metadata:
  name: search
  namespace: default
  labels:
    app: search
spec:
  ports:
  - name: http
    port: 9200
    nodePort:
  selector:
    app: search
---
apiVersion: v1
kind: Service
metadata:
  name: search-discovery
  namespace: default
  labels:
    app: search-discovery
spec:
  selector:
    app: search
  ports:
    - name: transport
      port: 9300
      protocol: TCP
      nodePort:
  clusterIP: None